# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('painel', '0006_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True, verbose_name='Título')),
                ('data_album', models.DateField(verbose_name='Data do Evento')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Foto')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.Album')),
            ],
        ),
    ]
