# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0007_album_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, verbose_name='Categoria'),
        ),
    ]
