# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170413_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='agencia',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='is_visualizada',
            field=models.BooleanField(default=False, verbose_name='Visualizada ?'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='modalidade',
            field=models.CharField(choices=[(1, 'Boleto bancário'), (2, 'Pagamento em Espécie'), (3, 'Depósito bancário'), (4, 'Débito automático')], default=1, max_length=20, verbose_name='Modalidade de Pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doacao',
            name='titular',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titular'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Valor doado mensalmente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
