# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170413_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='bairro',
            field=models.CharField(default=1, max_length=50, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doacao',
            name='cidade',
            field=models.CharField(default=1, max_length=50, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doacao',
            name='estado',
            field=models.CharField(default=1, max_length=2, verbose_name='UF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doacao',
            name='modalidade',
            field=models.CharField(choices=[('1', 'Boleto bancário'), ('2', 'Pagamento em Espécie'), ('3', 'Depósito bancário'), ('4', 'Débito automático')], max_length=20, verbose_name='Modalidade de Pagamento'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='rua',
            field=models.CharField(default=1, max_length=255, verbose_name='Rua'),
            preserve_default=False,
        ),
    ]
