# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170413_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='valor',
            field=models.CharField(max_length=255, verbose_name='Valor doado mensalmente'),
        ),
    ]
